server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://220.90.135.109:62543/post_test
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect