services:
  postgres:
    image: 'postgres:latest'
    container_name: 'real'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=mydatabase'
    ports:
      - 5555:5432
    restart: always
