management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  endpoint:
    health:
      show-details: always

  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
      base-path: "/manage"

  server:
    port: 9292

info:
  app:
    name: hello-actuator
    company: mh

logging:
  level:
    hello.controller: debug
